# Generated by Django 5.0.3 on 2024-03-27 13:08

import django.contrib.postgres.indexes
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_title_id', models.CharField(max_length=40)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['cate_title_id'], name='blogpost_ca_cate_ti_a4fa64_gin')],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('description', tinymce.models.HTMLField()),
                ('pub_date', models.DateField()),
                ('author_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('blog_image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('cate_title_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogpost.category')),
                ('tag_title', models.ManyToManyField(to='blogpost.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', tinymce.models.HTMLField()),
                ('pub_date', models.DateField()),
                ('author_name', models.CharField(max_length=40)),
                ('blog_image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('tag_title', models.CharField(max_length=40)),
                ('cate_title_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['pub_date', 'title'], name='blogpost_po_pub_dat_068496_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.CharField(max_length=50)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogpost.blog')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [django.contrib.postgres.indexes.HashIndex(fields=['name'], name='blogpost_co_name_4ae4e5_hash')],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['title'], name='blogpost_bl_title_34c50f_idx'),
        ),
    ]
