# Generated by Django 5.0.3 on 2024-03-28 10:37

import tinymce.models
from django.db import migrations, models

MATERIALIZED_VIEW_SQL = """
CREATE MATERIALIZED VIEW blogpost_materializedviewsblog AS
SELECT * FROM blogsspost_blog WHERE pub_date > '2024-03-14';
"""


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Materializedviewsblog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("description", tinymce.models.HTMLField()),
                ("pub_date", models.DateField()),
                ("author_name", models.CharField(max_length=40)),
            ],
        ),
    ]
